# Generated by Django 5.2.6 on 2025-09-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date_registered', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50)),
                ('date_of_event', models.DateField()),
                ('max_participants', models.IntegerField()),
                ('student', models.ManyToManyField(through='CreateEvent.AttendEvent', to='User.student')),
                ('teacher', models.ManyToManyField(to='User.teacher')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.room')),
            ],
        ),
        migrations.AddField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.event'),
        ),
    ]
