# Generated by Django 5.2.6 on 2025-09-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0001_initial'),
        ('User', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CreateEvent.event'),
        ),
        migrations.AlterField(
            model_name='attendevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User.student'),
        ),
    ]
