# Generated by Django 5.2.6 on 2025-12-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0003_alter_event_event_title_alter_event_max_participants'),
        ('User', '0003_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.event'),
        ),
        migrations.AlterField(
            model_name='attendevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student',
            field=models.ManyToManyField(related_name='attend', through='CreateEvent.AttendEvent', to='User.student'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='teacher',
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.teacher'),
        ),
    ]
