# Generated by Django 5.2.6 on 2025-09-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.account')),
                ('course', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=1)),
                ('department', models.CharField(max_length=15)),
            ],
            bases=('User.account',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.account')),
                ('age', models.IntegerField(default=0)),
            ],
            bases=('User.account',),
        ),
    ]
